GET http://localhost:8000/api/posts
###
GET http://localhost:8000/api/posts/10
###
POST http://localhost:8000/api/posts
Content-Type: application/json

{
    "title" : "PHP 8.3 Post",
    "description" : "Hello , World !"
}